# Generated by Django 3.2.4 on 2022-09-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_mcart_morder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='mobile',
            new_name='mob',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='passwd',
            new_name='passw',
        ),
    ]
